QubesOS/qubesos.github.io

_config.yml, _includes/footer.html
While this won't get rid of the endlessly unsolvable CAPTCHA that @mdik brought up in #1 it helps users find the hidden service URL once at the site so they can choose to revisit over Tor
=> added .onion mirror url for site to footer, issue #1

Makefile
* `jekyll build` takes its time to complete and `jekyll serve --watch`
only recompiles the changed files.
=> Use `jekyll serve --watch` to make testing faster.

pages/team.md
the current language is unclear whether "proprietary" refers to working on Windows (which is proprietary) or the code itself is proprietary (which has previously been the case).
Soon the Windows Tools will be open sourced, but for now (and always) it may be more clear just to refer to these developers as "Windows Tools" developers.
=> change "proprietary code" to "windows tools" devs

pages/home.html
The current link on the homepage leads to a 404.
=> Fix link to Whonix documentation from the homepage.

pages/help.md
user reports that StackOverflow is not appropriate for users (targeted at devs), also has no content re: Qubes:
https://groups.google.com/d/msgid/qubes-users/d92b4850-b951-44bc-b4d2-0d01a120db8a%40googlegroups.com
StackOverflow: https://stackoverflow.com/questions/tagged/qubes
vs: 
StackExchange: https://stackexchange.com/search?q=qubes
in the longer term we should consider trying to create a qubes.stackexchange.com
cc @bnvk
=> Stack Overflow --> Stack Exchange

pages/help.md
because freenode blocks tor connections, which are default on Qubes.
see: https://github.com/QubesOS/qubes-issues/issues/1571
=> changed unofficial IRC channel to OTFC

_data/downloads.yml, _layouts/downloads.html, pages/downloads.md, pages/getting-started.md
I've moved everything that was text and Markdown into the data file.
I've also taken the liberty of making sure that we have a stunning download page, which takes the user step-by-step through the process, from getting the image to the moment the OS is running on his computer.
I'm not expecting this to be merged "as-is", rather I expect this to generate review improvement requests from you, and then we will be able to merge it.
If you want to see how it looks, launch jekyll serve on a checkout of this branch.  I assure you, you will be shocked.
=> Make the Qubes OS downloads page fully data driven and beautiful

Gemfile
This repository depends on jekyll, json and a jekyll plugin. Gemfiles are used by [Bundler](http://bundler.io/) to manage ruby dependencies. 
Issue the following commands to make use of bundler for `qubesos.github.io`
~~~
gem install bundler
cd qubesos.github.io
bundle install
bundle exec jekyll serve
~~~
`bundle exec jekyll serve` executes the command in the context of qubesos.github.io. This is helpful if one want's to fix the Jekyll version or uses another Jekyll version on the system for another project.
=> Gemfile for bundler

.travis.yml, _data/architecture.yml, _data/downloads.yml, _data/team.yml, _includes/footer.html, _includes/head.html, js/jquery.toc.js, pages/downloads.md, pages/getting-started.md
Run `html-proofer` on every push.
This PR fixes also a bunch of links (in some cases by removing obsolete parts of page footer...)
One important change is change to ToC generating script - to preserve existing `id`, instead of replacing them with `tocAnchor-....`. This looks much nicer, but at the same time break old section links...
See individual commits for details.
=> Travis support, ToC links change

pages/donate.md
@andrewdavidwong can you check this out? there might we ways to improve this, like have two big buttons at the top of Bitcoin or Credit Card that jump the reader to the appropriate section.
OC logo here: https://opencollective.com/public/images/opencollectivelogo.png
this is to close: https://github.com/QubesOS/qubes-issues/issues/1434
=> add mention of OC CC method

pages/mailing-lists.md
@andrewdavidwong it would be awesome if we had that side bar that listed all the H1 headers and were clickable, with: qubes-announce, qubes-users, qubes-devel, qubes-project. Otherwise the page is a lot text to navigate. Not sure if we did away with those for some other reason.
=> added qubes-project mailing list

pages/statistics.md
It's weird that this page is named "counter" since it is otherwise referred to as Statistics. This fixes that, and provides a redirect from /counter so existing links don't break.
=> change name of page to "statistics", add redirect

Makefile
Using [bundle exec](https://bundler.io/man/bundle-exec.1.html) is the [recommended way](https://help.github.com/articles/setting-up-your-github-pages-site-locally-with-jekyll/#step-4-build-your-local-jekyll-site) to invoke jekyll.
=> Use bundle exec for jekyll invocations in Makefile

_data/research.yml
http->https://blog.invisiblethings.org
http->https://invisiblethings.org
(https://www.invisiblethings.org redirects to http, so I switched to https://invisiblethings.org)
http->https://tjd.phlegethon.org
http->https://www.ssi.gouv.fr
=> Rewriting http:// urls to https:// if they support it

Makefile
So that warnings are actually noticed instead of instantly scrolling off the screen.
=> Reduce jekyll build verbosity

pages/mailing-lists.md
It's not necessary anymore to point Debian users to Icedove, the
trademark issue has been resolved and the Thunderbird package is
included since oldstable. Less confusion possible
=> Mailinglists: remove references to Icedove

pages/mailing-lists.md
Qubes Translation mailing list was created but is still missing on the Qubes documentation. It was discussed to be added [1]. This is a pull requests for the the added qubes-translation mailing list.
[1] https://github.com/QubesOS/qubes-issues/issues/2824#issuecomment-305296334
=> Added qubes-translation mailing list

.travis.yml
Do not start from what travis have downloaded, because in case of PR we
expect to build the old version first (but travis have downloaded new
one already).
Fixes QubesOS/qubes-issues#2935
=> travis: use separate working directory for main repo too

_sass/_base.scss, _sass/_toc.scss
This was causing problems for example in links in headers, as seen (before this commit) in:
- https://www.qubes-os.org/doc/qubes-builder-details/
The only regression I saw was for the size of entries in the auto-generated table-of-contents on docs pages (which I've fixed). There may be other regressions, but I think this is the right approach regardless and there is a clear existing problem it addresses.
=> Keep links the same font size as the text they appear in

.travis.yml, _utils/spellcheck.sh, _utils/travis.sh
Differential spell checking
This script does not attempt to find all misspellings, but rather show when new words not previously known are introduced. This means it's useful in a continuous integration pipeline where we don't necessarily want each contributor to have to be responsible for the bad spelling of whoever came before them, but rather at least not make things worse. The existing spelling can then be incrementally cleaned up.
This approach also means we don't need to maintain a local dictionary to avoid false-positives, because existing "misspelled words" ("AppVM", "marmarek", etc.) will be ignored.
In addition, effort is made to only check prose, not code. All the actual parsing logic is handled by pandoc, and we just filter and transform a JSON AST that it produces.
We also …
=> Spell checking redux

_utils/travis.sh
Any objections, @marmarek?
> Adds the '--only_4xx' option to HTMLProofer, which "Only reports errors
> for links that fall within the 4xx status code range." [1] The rationale
> is that Travis CI should not fail just because there are successful
> redirects.
> 
> In particular, redirects from unversioned URLs to versioned URLs are
> desirable to support release-specific documentation (see
> QubesOS/qubes-issues#5308).
> 
> [1] https://github.com/gjtorikian/html-proofer#configuration
=> Use --only_4xx to prevent failure on successful redirects

_includes/hcl-cell.html
The previous behavior is retained, but now you can specify a `status` key which is whatever would've been there before (no/yes/partial/etc.) which defines the color, and a `message` key which is what actually shows in the cell in the final HTML. I patched this mostly because I was in the middle of updating someone's HCL report for the laptop I'm using, and I wanted to use this exact functionality.
This needs to be documented somewhere but I'm still not sure what the best place to do that is...
=> Allow setting custom messages in HCL cells

css/main.scss
- Reenable word wrap. Everything becomes super wide otherwise, and
even normally not-wide tables break badly.
- Use "display: table". This makes the table go outside of normal
layout, but doesn't hide the scrollbar (with "display: block",
the scrollbar is attached to the table, potentially several
screens down).
- Make sure table rows aren't transparent to fix glitches from
going outside of normal layout.
=> Slightly improve wide tables usablility

_includes/head.html
Starting with the release of [Tor Browser 9.5](https://blog.torproject.org/new-release-tor-browser-95), websites can have their alternate .onion addresses advertised to Tor desktop users who have the 'Onion Location' option enabled.
Sites that add the .onion address advertisement HTTP header can prompt their visitors to switch to a version delivered using the Onion service for improved security.
Final result:
=> Add Onion-Location meta tag

_includes/head.html
The Onion-Location is set as a meta tag but is hard-coded to the front page. If a user is on another page on the site and decides to switch to the onion, they'll be taken to the front page rather than the onion equivalent of the current page.
See the docs at https://community.torproject.org/onion-services/advanced/onion-location/ which demonstrate header-based use with $request_uri / %{REQUEST_URI} (nginx/apache)
This fixes the issue (I hope!) by re-using your 'canonical' tag's method in the template to find the current URL.
=> Append the path to the active page in the Onion-Location header 

_includes/doc-external-warning.html, css/main.scss
**The problem you're addressing (if any)**
Sharing a anchor link to an external documentation (within qubes-os.org/doc) page bypasses the warning to exercise caution (standard anchor link). Example: https://www.qubes-os.org/doc/network-bridge-support/#qubes-manager-patch-qubes-r2b2 (simply by using the anchor link to a lower part of the page). Anchor links are often shared in the support grups and I've found myself not noticing the warning.
Even though users are warned not to trust the website (distrust the infrastructure moto), in practice, I think most people coming to Qubes have no better alternative than to trust the website. So I'd argue it's better to show the warning at all times. (This has also happened to myself and even with me distrusting the website, it's good to have the …
=> Make External Documentation Warning Sticky

_data/team.yml
Marta's github was linking to https://github.com/marta instead of https://github.com/marmarta on the team page https://www.qubes-os.org/team/
=> fix Marta's github

pages/partners.md
On the [partners](https://www.qubes-os.org/partners/) page, the NLnet section contains a markdown link whereas it should be an html link.
Original error in fe3704fc069ef7c7eb08b9025a6efdf3aa9b965a
=> fix NLnet link (md -> html)

_utils/review-ok, _utils/review-verify
1. `review-ok` post a review on github with clearsigned message
including reviewed commit hash
2. `review-verify` downloads that review and verifies signature, then
compares with the current commit at that PR
The review-ok script takes Github API token from ~/.config/hub (a
config for the `hub` tool).
The review-verify script uses default gpg keyring and expects trusted
keys to be marked as such ("ultimate" or "fully"). Split GPG can be used
by setting GNUPG env variable to qubes-gpg-client-wrapper.
@andrewdavidwong here is also the script for you.
=> Add helper scripts for signed reviews

_data/teamtexts.yml, _includes/team.html
Fixes https://github.com/QubesOS/qubes-issues/issues/6533
=> Added link to Qubes Mailing Lists

_data/index.yml
Guide is the result of an effort made in https://qubes-os.discourse.group/t/best-split-ssh-setup-guide/385/ (some months ago)
This change was previously made in https://github.com/QubesOS/qubes-doc/pull/1106/ but somehow got revered.
If this revert turns out to be more wide-spread (expanded upon [in this issue](https://github.com/QubesOS/qubes-issues/issues/6605)), please disregard this PR and address the root issue.
=> replace split ssh with community docs

_includes/doc-index.html, _layouts/doc.html
Make it produce less white spaces/empty lines and make it work with translated pages.
See individual commits for details.
=> doc index improvements

_includes/variables.html
Fixes QubesOS/qubes-issues#6734
=> Website: (Re-)Include site-wide variables only where necessary

pages/donate.md
* Original link to Open Collective's FAQ has been dead since ~2018
* Info/documentation generally moved to opencollective.foundation
=> Fix Open Collective link in Donate page

_includes/hcl-device.html
This is a better solution than [PR 198](https://github.com/QubesOS/qubesos.github.io/pull/198). 
Instead of changing the structure of the slugs, we add the version index to the end of it if there is more than one version. I tested this locally and recommend to go ahead with this solution as it doesn't break any links but still introduces unique links for each report.
=> unique HCL URLs (slugs)

_data/team.yml
I use a Nitrokey to generate and store my private key. When re-flashing my Heads install, I answered some of the prompts without fully comprehending my actions and accidentally wiped my private key.
I no longer have access to it and needed to generate [a new one](https://keys.openpgp.org/vks/v1/by-fingerprint/0C276715E93D4CE54007BDBF54EB584E8668B05F). This new key is signed by an [older key](https://keys.openpgp.org/vks/v1/by-fingerprint/D7CAF2DB658D89BC08D6A7AADA6E167B8F541FB6), which is known to several of my contacts. It is also signed using my [Qubes Documentation Signing Key](https://github.com/QubesOS/qubes-secpack/blob/main/keys/doc-signing/sven-qubes-doc-signing-keys.asc), which in turn was previously signed by [the lost key](https://keys.openpgp.org/vks/v1/by-fingerprint/DA5975C9A …
=> change my public key (again)

.well-known/security.txt, _config.yml
Copy-pasting @andrewdavidwong content, and following @SaswatPadhi instructions, only changing the expiration date (first proposition was +4 years).
See:
- QubesOS/qubes-issues#7022
- https://forum.qubes-os.org/t/github-issue-7022-provide-https-qubes-os-org-well-known-security-txt/26972
=> Add .well-known/security.txt file, closes QubesOS/qubes-issues#7022
