_sass/_layout.scss
Change font sizes in headers to make greater differentiation between H1,H2 and H3.
Closes QubesOS/qubes-issues#1039
=> Change font sizes in h1-h6 for clarity

pages/people.md
feel free to change description @rootkovska
=> adding myself to people/team page

pages/donate.md
following: https://github.com/QubesOS/qubes-issues/issues/1246
=> rewrite donations page to be less scary

_sass/_home.scss, _sass/_variables.scss, css/main.scss, pages/home.html
@rootkovska @marmarek @mfc here is my first full pass at implementing the new site design as per #1460 and #1207 
As mentioned a couple days ago, a few sub-pages are less than ideal, but I got the homepage looking 97% of the way towards the design comps I sent last week! 
Note: I messed up with the properly tagging the issue in all the commit messages. I tried going back in the history to edit them using `git rebase -i` as per [this tip](http://stackoverflow.com/questions/179123/edit-an-incorrect-commit-message-in-git) but it was seeming a bit. If this is really important, I can keep fiddling with it, but I believe putting my effort to other things might be more important (e.g. reworking News section) given I'm already behind schedule on this!
=> New website design

pages/team.md
=> added brennan

pages/home.html
fixed two typos, added mailing list to Contact section
=> fixed two typos, added mailing list

_data/team.yml, _includes/team-simple.html, _sass/_extras.scss, _sass/_pages.scss, css/main.scss, pages/team.md
This is my first pass at refactoring the team page on the public site! I think it's a bit of improvement over the existing and takes into account most of Joanna's thoughts!
=> Refactored and styled Team page

_includes/hcl-cell.html, _includes/hcl-color.css, _includes/hcl-device.html, _includes/hcl-item.html, _includes/hcl-version.html, _layouts/full.html, _sass/_pages.scss, pages/compatible-hardware.html
In this pull request I modified the HCL page a bit as per Joanna's request!
- User nicer colors for differing states of supported features
- Added various Bootstraps `.table` classes to improve overall style
- Refactored legend / glossary at top to look better
- Removed a bunch of whitespace and normalized table HTML
=> Refactored HCL page to look nicer

pages/home.html
=> updated download description to 3.1

_sass/_header.scss
=> Fixed navbar button - border radius

_data/research.yml, pages/research.md
=> Finish making Research page and section data-driven

_data/news.yml
@bnvk, this file is no longer being used, right?
=> Remove old _data/news.yml

pages/jobs.md, pages/join.md
=> Create Jobs page (QubesOS/qubes-issues#1700)

pages/mailing-lists.md
Add information about how to subscribe to the mailing lists using Gmane. I think that the text needs to be reworded to make it "flow" better.
=> Add information about Gmane

pages/funding.md
added small blurbs to each funder.
re: ITL, weird to list only one owner of the company since they are both on the team (and team page), fixed that.
=> added small blurbs

_data/team.yml
=> updated pgp key

pages/home.html
=> Endorsements update

pages/funding.md
next up we need to add support tiers.
=> split funding by year

pages/partners.md
ordered by amount, non-monetary contributions converted into dollar equivalent. headers for orgs necessary to link to them from the new funding page.
=> new version of partners page

pages/funding.md
@andrewdavidwong please review, interested in your thoughts. see email as well.
=> new version of funding page (commit #2)

pages/gsoc.md
they don't look good on website
=> removed "checkboxes"

pages/code-of-conduct.md
to implement https://github.com/QubesOS/qubes-issues/issues/2163. it would not yet be linked to from any page, we would share it with qubes-project list to solicit more feedback.
=> Create code of conduct

pages/code-of-conduct.md
https://github.com/QubesOS/qubes-issues/issues/2163#issuecomment-278297127
=> Add "A note on trust" to the code of conduct

pages/gsoc.md
+ added some details for Whonix projects.
+ added Marek as mentor for GNOME since no one else has stepped up..
=> moved projects without mentors to the bottom

pages/gsoc.md
Based on my repies to posts by prospective GSoC students on qubes-devel.
=> Add recommendations for GSoC students

_utils/update-submodules
To make it hard to accidentally use unverified files.
Like https://github.com/QubesOS/qubes-builder/commit/0cc5d570b8c3dbebfbccde7d1f6d2ffa5596e8ca
```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256
Also, I'm using a new signing key for my docs commits starting now: Thu Mar 16 06:17:09 UTC 2017
New key is:
pub   rsa4096 2016-12-31 [SC]
F4E85FD3674665A209050713E0C9723C50A46274
uid           [ultimate] Jean-Philippe Ouellet (Qubes OS Documentation Signing Key #1) <jpo@vt.edu>
- -----BEGIN PGP PUBLIC KEY BLOCK-----
mQINBFhm9WkBEADWvkuHpV4xnVVBOnWuxLivNo4UgZQZ3K8W+dZAbhKj3YFiYR3H
oUwDUtyjKCl8QeNGR9j88vLNsTAu2d4zvyw1fVdCbgif6ZFlTbt5aOWpiSln0AlM
zac7IY3wyJtw1o3FXf7tLFxti9eu7+sv4gdO9b7843uwqP4p3Dm7CsrDkzJ1l5hI
A2t1Ivgp3VosXf+eZ5f1Ydb+4ZX562tlBcjvRtQ+nHU26Zhevm7tjmcs4yFSn6s0 …
```
=> Remove FETCH_HEAD ref if verification failed

.travis.yml, _data/downloads.yml, pages/downloads.md
Fixes https://github.com/QubesOS/qubes-issues/issues/2752
=> Fix mirror links

_data/team.yml
=> Update team.yml (http:// -> https://)

pages/home.html
=> Update home.html (http:// -> https://)

pages/intro.md
=> Update intro.md (http:// -> https://) 

pages/hcl.html
=> Update hcl.html (http:// -> https://)

pages/getting-started.md
Should https://theinvisiblethings.blogspot.com/2011/03/partitioning-my-digital-life-into.html be changed to https://blog.invisiblethings.org/2011/03/13/partitioning-my-digital-life-into.html?
------
=> Update getting-started.md (http:// -> https://)

pages/screenshots.md
Should https://theinvisiblethings.blogspot.com/2013/02/converting-untrusted-pdfs-into-trusted.html
be replaced with
https://blog.invisiblethings.org/2013/02/21/converting-untrusted-pdfs-into-trusted.html ?
--
=> Update screenshots.md  (http:// -> https://)

pages/partners.md
=> Small typo fix

_data/architecture.yml, _sass/_pages.scss, pages/donate.md, pages/partners.md
This is an unreviewed cherry-pick of @katsinger's https://github.com/QubesOS/qubesos.github.io/pull/91 / https://github.com/QubesOS/qubesos.github.io/pull/106, with a few formatting nitpicks.
Git usage is cleaned up, rebased, and conflicts resolved, so now it's in a merge-able state if the content changes are approved.
/cc @mfc @andrewdavidwong 
see also: https://github.com/QubesOS/qubes-issues/issues/1701
xref: https://github.com/QubesOS/qubesos.github.io/pull/65 https://github.com/QubesOS/qubesos.github.io/pull/67 https://github.com/QubesOS/qubesos.github.io/pull/68
=> Funding rewrite by @katsinger

_data/team.yml
I still don't plan to use this one regularly for all email, but
might as well have a limited-scope one for when it's useful.
```
pub   rsa4096 2017-12-31 [SC]
C37B75A11DC7C9CC6CD5B7A9AFE6E6A3D6EE7AD6
uid           [ unknown] Jean-Philippe Ouellet (Qubes OS Correspondence Key #1) <jpo@vt.edu>
sub   rsa4096 2017-12-31 [E]
```
```
-----BEGIN PGP PUBLIC KEY BLOCK-----
mQINBFpIKNEBEAC0lqTkWWZkxeXLeX11TrI6Qhbk1PNEr5WI8o48PmK4H53Sv9Ai
1F/vO6qqAUDkpUjP1BtA6G3RTir4LXm28g4yCtCiBPQ7zuaQu4v87koWqH9g/jsf
8b6meajneZX50BRf9i5hr98ZIPvt5nPYmAgnYWcvnM2osm5JhylDMfYB/+oYQNnP
k768vrvirWQ2XFfPIXWbtORS9EHjOnlyqh+yJuBlXXusV/Y35lZNULoMOkbqLfal
2qiyLBvZFDObWc9oIPHoVGiHl8CVK5QaqP8CpuYjhuuzqvlXEYfzAnhWEp6GIODu
D9Sq1pNtsaqIyGpJW15GTeeqwkASMGL9TbhPolwz0M3VjFrFjKw14xhoA0IEu1mM …
```
=> Add qubes-specific pgp key for myself (@jpouellet)

_data/downloads.yml
@andrewdavidwong here is an update for the URLs. Actual files are already uploaded.
Can you merge it and announce (again - no real changes since 4.0.3-rc1, and only very minimal since 4.0.2)?
=> Release Qubes 4.0.3

pages/partners.md
Mullvad is already mentioned in list of donations for 2020, but in their description was only 2017 mentioned.
=> Updated mullvad info with the donation in 2020

pages/partners.md
Partners subpage updated with Piston's donation
=> Donation 10k+ from Piston in 2020

_includes/header.html, css/main.scss, pages/downloads.html
Updates requested in https://github.com/QubesOS/qubes-issues/issues/5732.
CC: @ninavizz, @marmarta
=> Update website for survey

_data/team.yml
@marmarek @andrewdavidwong please add/edit more specific role.
photo (from github) merge request is here: https://github.com/QubesOS/qubes-attachment/pull/43
=> adding Demi to team page

_data/includes.yml
Found by [another user on the forum](https://qubes-os.discourse.group/t/typo-on-website-durckduckgo/3541)
=> Typo "duRckduckgo"

_data/index.yml
Discussed in https://github.com/QubesOS/qubes-issues/issues/6426
=> Added Screen Sharing

pages/partners.html
see: https://github.com/QubesOS/qubes-issues/issues/6546
=> add CCT and Discourse

_includes/footer.html, js/sorttable.js
Uses sorttable, by Stuart Langridge, under the X11 License:
https://kryogenix.org/code/browser/sorttable/
See QubesOS/qubes-issues#3795 for discussion.
=> Make HCL tables sortable

_includes/doc-widget.html
Fixes issue [#6578](https://github.com/QubesOS/qubes-issues/issues/6578).
=> Fix broken "Edit This Page" widget

_data/team.yml
I don't know if it is too early, but I would be honored and very motivated by being included as a community contributor
=> add Sven as HCL maintainer

pages/donate.md
Following discussion https://qubes-os.discourse.group/t/donation-to-qubes-os/3878/12
=> mention paypal is supported as well

_data/team.yml
... transition to hardware based key (Nitrokey, internally generated key). Won't change again any time soon (years). Sorry.
=> Sven: new fingerprint

pages/donate.md
Note: Monero icon depends on https://github.com/QubesOS/qubesos.github.io/pull/160.
=> Add Monero donation information

_config.yml, _data/architecture.yml, _data/index.yml, _includes/doc-content.html, _includes/style-guide.html, _layouts/doc-index.html
Issue: https://github.com/QubesOS/qubes-issues/issues/6701
qubes-doc companion PR: https://github.com/QubesOS/qubes-doc/pull/1156
=> Automatically generate as much of the documentation's "metadata" as possible

_includes/team-pgp.html, _includes/team-simple.html, _includes/team.html
Fixes QubesOS/qubes-issues#6746
=> Abstract out PGP key links and update keyserver URL

_data/index.yml
Related: https://github.com/QubesOS/qubes-doc/pull/1031.
=> Add link to Template Manager design docs

pages/home.html
Closes QubesOS/qubes-issues#6936
=> Update "join the community" section

_data/visual-style-guide-page.yml
Fixes dead link to Font Awesome's website and separates the words "Font" and "Awesome" as that's how they refer to themselves.
=> Update Font Awesome URL

pages/partners.html
- Wrap text
- Improve source formatting
- Remove unnecessary hardcoded heading IDs
=> Clean up source

pages/donate.md
Other related PRs:
https://github.com/QubesOS/qubes-secpack/pull/57 (update qubes-secpack file)
https://github.com/QubesOS/qubes-posts/pull/101 (news announcement)
=> Add Ethereum donation address

pages/donate.md
- Improve layout and formatting
- Add cryptocurrency donation address QR codes
=> Update donation page

_data/team.yml
=> update my description to include "Qubes Forum moderator"

_data/team.yml
I asked for volunteers to take over my website and documentation maintainer roles. @unman kindly volunteered to take on both roles.
Forum thread: https://forum.qubes-os.org/t/18457
=> Make @unman the new website and documentation maintainer

pages/partners.html
Logos added in https://github.com/QubesOS/qubes-attachment/commit/cb618d8502ab0a2aeaf8544c988f1a9cb274919c
=> Add Tether and Bitfinex to Qubes Partners page

pages/partners.html
- Update 2022 and 2023 Partner lists
- Add Partner entry for Equinix
- Fix alphabetical subsorting
- Make links and bolding consistent across entries
- Unwrap paragraph text
- Replace tabs with spaces
=> Update Qubes Partners page

pages/home.html
Depends on: https://github.com/QubesOS/qubes-attachment/pull/65
Solves task 1, 2 from: https://github.com/QubesOS/qubes-issues/issues/8234
=> Update home.html - change {nlnet,OTF-logo}.gif to {nlnet,OTF-logo}.svg

_data/doc-index.yml
related to https://github.com/QubesOS/qubes-doc/pull/1353
=> Add new GUI development article

_data/doc-index.yml
https://github.com/QubesOS/qubes-doc/pull/1319
=> Remove the obsolete /doc/profiling/ site

_data/downloads.yml
=> R4.2.1 download links

_data/team.yml
Hi!
I'm putting myself down for Qvm-Create-Windows-Qube and Qubes Video Companion. The list appears to be ordered alphabetically by last name so I just slotted myself in there.
Thank you!
=> Add myself as a community contributor

_data/downloads.yml
https://github.com/QubesOS/qubes-issues/issues/9316
=> Add R4.2.2-rc1 download links

_data/downloads.yml
=> Add R4.2.3-rc1 download links

_data/downloads.yml
=> Add R4.2.3 download links

_data/team.yml
=> Add new documentation maintainers

_data/downloads.yml
=> Add R4.2.4-rc1 download links

_data/downloads.yml
The kernel.org links don't work yet, but should in a few hours
=> Download links for R4.2.4

pages/donate.md
based on internal discussions & with CCT, in reference to: https://forum.qubes-os.org/t/donation-via-eu-bank-transfer/21208
=> removed 500EUR minimum for EU bank transfer

pages/donate.md
current link redirects to this, so lets set it directly.
=> Donate: update Gnosis Safe link

_data/downloads.yml
=> R4.3.0-rc2 download links

_data/team.yml
- I don't have that email yet
- The title is using the same as other members (kinda)
- The key is my coding signing key, not my mail sign+encrypt key
=> Join the team
